name: Send Message to Webhook

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  sendMessage:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Webhook
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "content": "Hello, this is a test message from GitHub Actions!"
          }' https://discord.com/api/webhooks/1293396344681271360/Gq-lNfFGPOQufT7d19MQL43JllPVqeorYiakMa0HmvRrPkhUJL3cSg0aaIiVC1Lm6A-h  # Replace with your webhook URL
