name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "content": "New commit}' https://discord.com/api/webhooks/1293396344681271360/Gq-lNfFGPOQufT7d19MQL43JllPVqeorYiakMa0HmvRrPkhUJL3cSg0aaIiVC1Lm6A-h
