name: Send Commit Data to Webhook

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  sendMessage:
    runs-on: ubuntu-latest
    steps:
      - name: Send Commit Data to Webhook
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "content": "New commit on `'${{ github.repository }}'` by `'${{ github.actor }}'`: [Commit: `'${{ github.sha }}'`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\\nMessage: `'${{ github.event.head_commit.message }}'`"
          }' https://discord.com/api/webhooks/123456789012345678/abcdefghijklmnopqrstuvwxyz  # Replace with your webhook URL
